/*
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * pve-modkit loader (ext.js)
 * -------------------------------------------------------------------------
 * Injected into the Proxmox VE web UI via a single <script> tag placed just
 * before </head> in index.html.tpl:
 *
 *     <script src="/modkit/ext.js" data-pve-modkit="loader"></script>
 *
 * It loads after pvemanagerlib.js, so `Ext` and `PVE` are (or shortly become)
 * available. This loader fetches the mod manifest generated by
 * `pve-modkit index` (/modkit/index.json) and injects each enabled mod's
 * entry script.
 *
 * The /modkit/ URL prefix is a dedicated static dir key registered in
 * pveproxy.pm, mapped to /usr/share/pve-modkit/mods/. pveproxy's add_dirs
 * File::Find walk registers each per-mod subdirectory as its own served key,
 * so every mod lives in its own named subdir and is served at
 * /modkit/{mod}/{entry} (nested URLs work; the walk runs at pveproxy init).
 *
 * Manifest shape (enabled mods only):
 *     { "mods": [ { "name": "demo-logo-glow", "path": "demo-logo-glow/index.js" }, ... ] }
 *
 * Design goals: never break the Proxmox UI. All failures degrade gracefully
 * and are reported loudly to the console.
 */
(function () {
    "use strict";

    if (window.__pveModkitLoaded) {
        return;
    }
    window.__pveModkitLoaded = true;

    const MANIFEST_URL = "/modkit/index.json";
    const MODS_BASE = "/modkit/";

    function injectMod(mod) {
        // A manifest entry is { name, path } where path is "{mod}/{entry}"
        // relative to /modkit/. Tolerate a bare string for forward/backward
        // compatibility.
        const rel = (mod && typeof mod === "object") ? mod.path : mod;
        if (typeof rel !== "string" || rel === "") {
            console.error(
                "[pve-modkit] skipping mod with invalid path:", mod);
            return;
        }
        const s = document.createElement("script");
        s.src = MODS_BASE + rel;
        s.async = false; // preserve manifest order across injected scripts
        s.setAttribute("data-pve-modkit", "mod");
        if (mod && mod.name) {
            s.setAttribute("data-pve-modkit-name", String(mod.name));
        }
        s.onerror = function () {
            console.error(
                "[pve-modkit] failed to load mod:", s.src);
        };
        document.head.appendChild(s);
    }

    function loadMods(manifest) {
        const mods = (manifest && manifest.mods) || [];
        if (!Array.isArray(mods)) {
            console.error(
                "[pve-modkit] manifest 'mods' is not an array:", manifest);
            return;
        }
        mods.forEach(injectMod);
        console.info(`[pve-modkit] loaded ${  mods.length  } mod(s)`);
    }

    function fetchManifestFetch() {
        fetch(MANIFEST_URL, { cache: "no-cache" })
            .then((resp) => {
                if (!resp.ok) {
                    throw new Error(`HTTP ${  resp.status}`);
                }
                return resp.json();
            })
            .then(loadMods)
            .catch((err) => {
                console.error(
                    "[pve-modkit] failed to load mod manifest:",
                    MANIFEST_URL, err);
            });
    }

    function fetchManifestXHR() {
        try {
            const xhr = new XMLHttpRequest();
            xhr.open("GET", MANIFEST_URL, true);
            xhr.onreadystatechange = function () {
                if (xhr.readyState !== 4) {
                    return;
                }
                if (xhr.status >= 200 && xhr.status < 300) {
                    try {
                        loadMods(JSON.parse(xhr.responseText));
                    } catch (err) {
                        console.error(
                            "[pve-modkit] failed to parse mod manifest:",
                            MANIFEST_URL, err);
                    }
                } else {
                    console.error(
                        "[pve-modkit] failed to load mod manifest:",
                        MANIFEST_URL, `HTTP ${  xhr.status}`);
                }
            };
            xhr.send();
        } catch (err) {
            console.error(
                "[pve-modkit] failed to load mod manifest:",
                MANIFEST_URL, err);
        }
    }

    function start() {
        if (typeof window.fetch === "function") {
            fetchManifestFetch();
        } else {
            fetchManifestXHR();
        }
    }

    function boot() {
        if (window.Ext && typeof Ext.onReady === "function") {
            Ext.onReady(start);
        } else if (document.readyState === "loading") {
            document.addEventListener("DOMContentLoaded", start, { once: true });
        } else {
            start();
        }
    }

    boot();
})();
